identifier: k7yau1p7x8vfp8n2
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: analu-blog
homeFolder: C:\Users\sampa\Desktop\workspace\blog\analu.io\analu-blog
distFolder: ./dist/analu-blog
outDir: C:\Users\sampa\Desktop\workspace\blog\analu.io\analu-blog\dist\static
handle404: ''
allowErrorCollect: false
